services:
  api:
    build:
      context: ./storia-api
      target: development
    volumes:
      - ./storia-api:/src/app
      - /src/app/node_modules
    command: npm run dev
    # Não precisamos do healthcheck em dev, pois o nodemon cuida disso
    healthcheck:
      disable: true

  web:
    build:
      context: ./storia-cliente
      target: development # <--- ESSA LINHA É A MUDANÇA PRINCIPAL
    ports:
      - "5173:5173"
    volumes:
      - ./storia-cliente:/app
      - /app/node_modules
    # O comando continua o mesmo
    command: npm run dev